In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np


Problem - 1: Array Creation:

In [ ]:
#1. Initialize an empty array with size 2 × 2
import numpy as np

arr1 = np.empty((2,2))
print(arr1)


[[9.73593000e-316 0.00000000e+000]
 [6.79916842e-310 6.79916835e-310]]


In [ ]:
#Initialize an all one array with size 4 × 2
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Return a new array of given shape filled with a value (Hint: np.full)

arr3 = np.full((3,3), 7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Return a new array of zeros with same shape as given array (Hint: np.zeros_like)

arr4 = np.zeros_like(arr3)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# Return a new array of ones with same shape as given array (Hint: np.ones_like)

arr5 = np.ones_like(arr3)
print(arr5)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Convert list to NumPy array

new_list = [1,2,3,4]

arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
#1. Create an array with values ranging from 10 to 49 (Hint: np.arange())

arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8 {Hint:look for np.reshape()}
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
arr4 = np.random.random(30)
mean_value = arr4.mean()

print(arr4)
print("Mean:", mean_value)

[0.04156389 0.17130339 0.47034956 0.38146824 0.00980003 0.28949759
 0.90039519 0.47592245 0.53941926 0.17577908 0.59006393 0.67355821
 0.17441975 0.94321467 0.20637193 0.3764938  0.06838795 0.26184508
 0.6494506  0.61103969 0.08336772 0.62606049 0.05470526 0.35977719
 0.90853015 0.93235141 0.29587917 0.14581376 0.87912323 0.68579465]
Mean: 0.43272491039974437


In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
arr5 = np.random.random((10,10))

print(arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())


[[0.84726826 0.57057313 0.91064418 0.22403409 0.08834837 0.04240236
  0.38603791 0.42073737 0.20616796 0.61880107]
 [0.46310871 0.08530147 0.31330091 0.56154126 0.54004274 0.82920096
  0.93340732 0.08090742 0.63851991 0.56437905]
 [0.07050174 0.4179656  0.67719191 0.88614244 0.08714594 0.73764689
  0.25996367 0.62359349 0.88104994 0.84894431]
 [0.95161088 0.18769572 0.20223508 0.2336047  0.10449002 0.09014237
  0.72696007 0.67457212 0.87376413 0.14685045]
 [0.27993727 0.51397536 0.23572391 0.11054109 0.21495844 0.00098847
  0.36652877 0.24232309 0.69456718 0.45674878]
 [0.76980118 0.15785781 0.91769923 0.77610557 0.24077427 0.93097618
  0.4237804  0.33515846 0.3408716  0.61573496]
 [0.05777006 0.60003937 0.53666121 0.60572231 0.25280955 0.5709722
  0.4441947  0.13566305 0.70061981 0.07883789]
 [0.05681887 0.8898457  0.46583955 0.35186507 0.233765   0.32484705
  0.14429969 0.29806752 0.33654954 0.22906716]
 [0.92747367 0.7813831  0.52699275 0.85999498 0.05803799 0.61610852
  0.72766191 

In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.
arr6 = np.zeros(10)

arr6[4] = 1

print(arr6)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].
arr7 = np.array([1,2,0,0,4,0])
reversed_arr = arr7[::-1]

print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.
arr8 = np.ones((5,5))

arr8[1:-1,1:-1] = 0

print(arr8)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
arr9 = np.zeros((8,8), dtype=int)

arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1

print(arr9)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [ ]:
#1. Add the two array.
add_xy = x + y
print("Addition:\n", add_xy)

Addition:
 [[ 6  8]
 [10 13]]


In [ ]:
#2. Subtract the two array.
sub_xy = x - y
print("Subtraction:\n", sub_xy)

Subtraction:
 [[-4 -4]
 [-4 -3]]


In [ ]:
#3. Multiply the array with any integers of your choice.
mul_x = x * 10
print("Multiply x by 3:\n", mul_x)

Multiply x by 3:
 [[10 20]
 [30 50]]


In [ ]:
#4. Find the square of each element of the array.
square_x = x ** 2
print("Square of x:\n", square_x)

Square of x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
print("Dot product v·w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product x·v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product x·y:\n", dot_xy)

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]


In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
concat_xy = np.concatenate((x,y), axis=0)
print("Row concatenation:\n", concat_xy)

concat_vw = np.concatenate((v,w), axis=0).T
print("Row concatenation:\n", concat_vw)

#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
#Since x is 2D array (2×2) and v is 1D array so Concatenation requires same dimensions, so NumPy cannot combine them.
#To fix and solve we do,
v2 = v.reshape(1,2)
result = np.concatenate((x,v2))
print("x and v concatenation:\n", result)

Row concatenation:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Row concatenation:
 [ 9 10 11 12]
x and v concatenation:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


In [ ]:
#1. Prove A · A⁻¹ = I
A_inv = np.linalg.inv(A)

identity = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A^-1:\n", identity)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#2. Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [ ]:
#3. Prove (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇(AB)T=BTAT
left = np.transpose(np.dot(A,B))

right = np.dot(np.transpose(B), np.transpose(A))

print("Left (AB)^T:\n", left)
print("Right B^T A^T:\n", right)

Left (AB)^T:
 [[23 51]
 [13 29]]
Right B^T A^T:
 [[23 51]
 [13 29]]


In [ ]:
#• Solve the following system of Linear equation using Inverse Methods.

#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Solve using inverse
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution [x, y, z]:")
print(X)

Solution [x, y, z]:
[ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

In [ ]:
#Python List
import time

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python list addition time:", end-start)

#NumPy
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 + arr2

end = time.time()

print("NumPy addition time:", end-start)

Python list addition time: 0.1263141632080078
NumPy addition time: 0.019420862197875977


In [ ]:
#2. Element-wise Multiplication
#Python list
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python list multiplication time:", end-start)

#NumPy
start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy multiplication time:", end-start)

Python list multiplication time: 0.1163930892944336
NumPy multiplication time: 0.01527857780456543


In [ ]:
#3. Dot Product
#Python list
start = time.time()

dot = sum(list1[i]*list2[i] for i in range(size))

end = time.time()

print("Python dot product time:", end-start)

#NumPy
start = time.time()

dot = np.dot(arr1,arr2)

end = time.time()

print("NumPy dot product time:", end-start)

Python dot product time: 0.1133260726928711
NumPy dot product time: 0.0020682811737060547


In [ ]:
#4. Matrix Multiplication
#Python List
size = 100

A = [[1]*size for i in range(size)]
B = [[1]*size for i in range(size)]

start = time.time()

result = [[sum(A[i][k]*B[k][j] for k in range(size))
          for j in range(size)] for i in range(size)]

end = time.time()

print("Python matrix multiplication time:", end-start)

#NumPy
A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy matrix multiplication time:", end-start)

Python matrix multiplication time: 0.09063720703125
NumPy matrix multiplication time: 0.08428835868835449


Final Observation

From the observation we can see that numpy is much faster than python lists. In all the mathmatical operations, numpy gives faster result in comparison to the python lists. It is because NumPy uses optimized C implementation, it supports vectorized operations and uses efficient memory management.
